name: reflectable_flutter
description: A minimal example using reflectable with Flutter.
environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  reflectable: any
  build_runner: any
  built_value_generator: any

flutter:
  uses-material-design: true
